---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)
library(readxl)
library(cowplot)
```

```{r}
coefficients <- readxl::read_xlsx(here("data/waldron/13059_2018_1511_MOESM5_ESM.xlsx"),
                       sheet = 2,
                  skip =2) %>%
  janitor::clean_names()
```


```{r}
coefficients %>% 
  filter(grepl(variable, pattern = "CMS") | variable %in% c("MSI")) %>%
  ggplot(aes(pcss1_effect_size, pcss2_effect_size, color = variable)) + 
  geom_hline(yintercept = 0, linetype = "dashed") + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  geom_point(size = 2) +
  theme_cowplot() + 
  geom_errorbarh(aes(xmin = pcss1_effect_size-pcss1_standard_error, 
                     xmax = pcss1_effect_size+pcss1_standard_error)) +
  geom_errorbar(aes(ymin = pcss2_effect_size-pcss2_standard_error, 
                    ymax = pcss2_effect_size+pcss2_standard_error)) + 
  scale_color_brewer(type = 'qual', palette = 3) +
  theme(legend.position = 'bottom') + 
  labs(x = "PC Cluster Subtype Scores 1",
       y = "PC Cluster Subtype Scores 2",
       subtitle = "Statistics from fitting regression models with subtype scores to outcome variables",
       title = "PC Cluster Subtype Scores linked to CMS and MSI status") + 
  ggsave("cms_waldron.png", width = 8, height = 8)
  
  
```


```{r}
coefficients %>% 
  filter(grepl(variable, pattern = "MSI")) %>%
  ggplot(aes(pcss1_effect_size, pcss2_effect_size, color = variable)) + 
  geom_point() +
  theme_cowplot() + 
  geom_errorbarh(aes(xmin = pcss1_effect_size-pcss1_standard_error, 
                     xmax = pcss1_effect_size+pcss1_standard_error)) +
  geom_errorbar(aes(ymin = pcss2_effect_size-pcss2_standard_error, 
                    ymax = pcss2_effect_size+pcss2_standard_error))
```

